-- ROLLBACK;
BEGIN;

CREATE TABLE IF NOT EXISTS "vat_rate" (
    "vat_rate_id" SERIAL PRIMARY KEY,
    "rate" NUMERIC(6,4) NOT NULL,
    "start_date" DATE NOT NULL,
    "end_date" DATE
);

INSERT INTO "vat_rate" ("rate", "start_date") VALUES (0.23, CURRENT_DATE);

ALTER TABLE "course_in_order_item"
ADD COLUMN "price_at_order" DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
ADD COLUMN "vat_rate" NUMERIC(6,4) NOT NULL DEFAULT 0.00,
ADD COLUMN "net_total" DECIMAL(18, 2) NOT NULL DEFAULT 0.00,
ADD COLUMN "vat_total" NUMERIC(18,2) NOT NULL DEFAULT 0.00,
ADD COLUMN "gross_total" NUMERIC(18,2) NOT NULL DEFAULT 0.00,
ADD CONSTRAINT "chk_vat_rate_valid"
    CHECK ("vat_rate" >= 0 AND "vat_rate" <= 1),
ADD CONSTRAINT "chk_net_total_non_negative"
    CHECK ("net_total" >= 0),
ADD CONSTRAINT "chk_vat_total_non_negative"
    CHECK ("vat_total" >= 0),
ADD CONSTRAINT "chk_gross_total_non_negative"
    CHECK ("gross_total" >= 0),
ADD CONSTRAINT "chk_gross_total_consistency"
    CHECK ("gross_total" = "net_total" + "vat_total");

-- assuming the price has not changed while the system works
UPDATE "course_in_order_item"
SET
    "price_at_order" = c."price",
    "vat_rate" = 0.23,
    "net_total" = c."price",
    "vat_total" = c."price" * 0.23,
    "gross_total" = c."price" * 1.23
FROM "course" c
WHERE "course_in_order_item"."course_id" = c."course_id";


CREATE TABLE "invoice_order_item" (
    "invoice_order_item_id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
    "invoice_id" INTEGER NOT NULL,
    "course_in_order_item_id" INTEGER NOT NULL,
    "vat_rate" NUMERIC(6,4) NOT NULL,
    "net_total"  NUMERIC(18,2)  NOT NULL,
    "vat_total" NUMERIC(18,2) NOT NULL,
    "gross_total" NUMERIC(18,2) NOT NULL,
    PRIMARY KEY("invoice_order_item_id"),

    CONSTRAINT "fk_invoice_order_item_invoice"
        FOREIGN KEY("invoice_id")
        REFERENCES "invoice"("id")
        ON DELETE CASCADE,

    CONSTRAINT "fk_invoice_order_item_item"
        FOREIGN KEY("course_in_order_item_id")
        REFERENCES "course_in_order_item"("id")
        ON DELETE RESTRICT,

    CONSTRAINT "uq_invoice_item_pair"
        UNIQUE("invoice_id", "course_in_order_item_id"),

    CONSTRAINT "chk_vat_rate_valid"
        CHECK ("vat_rate" >= 0 AND "vat_rate" <= 1),
    CONSTRAINT "chk_net_total_non_negative"
        CHECK ("net_total" >= 0),
    CONSTRAINT "chk_vat_total_non_negative"
        CHECK ("vat_total" >= 0),
    CONSTRAINT "chk_gross_total_non_negative"
        CHECK ("gross_total" >= 0),
    CONSTRAINT "chk_gross_total_consistency"
        CHECK ("gross_total" = "net_total" + "vat_total")
);

INSERT INTO "invoice_order_item" ("invoice_id", "course_in_order_item_id", "vat_rate", "net_total", "vat_total", "gross_total")
SELECT
    i."id",
    coit."id",
    coit."vat_rate",
    coit."net_total",
    coit."vat_total",
    coit."gross_total"
FROM "invoice" i
JOIN "order_item" oi ON i."order_id" = oi."order_id"
JOIN "course_in_order_item" coit ON oi."order_item_id" = coit."order_item_id";


-- businesswise - these is unacceptable and should not be touched, but for the sake of the task, it has to be done
-- Consusion for the future: plan invoice and payment system thoroughly before implementing it
ALTER TABLE "invoice"
DROP CONSTRAINT "chk_invoice_totals",
DROP CONSTRAINT "chk_invoice_totals_math",
DROP COLUMN "vat_rate",
DROP COLUMN "vat_total",
DROP COLUMN "net_total",
DROP COLUMN "gross_total",
DROP COLUMN "order_id";

COMMIT;
