BEGIN;

ALTER TABLE "course_in_order_item"
ADD COLUMN "cost" NUMERIC(18,2) NOT NULL DEFAULT 0;

CREATE TABLE "invoice_order_item" (
    "invoice_order_item_id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
    "invoice_id" INTEGER NOT NULL,
    "course_in_order_item_id" INTEGER NOT NULL,
    PRIMARY KEY("invoice_order_item_id"),

    CONSTRAINT "fk_invoice_order_item_invoice"
        FOREIGN KEY("invoice_id")
        REFERENCES "invoice"("id")
        ON DELETE CASCADE,

    CONSTRAINT "fk_invoice_order_item_item"
        FOREIGN KEY("course_in_order_item_id")
        REFERENCES "course_in_order_item"("id")
        ON DELETE RESTRICT,

    CONSTRAINT "uq_invoice_item_pair"
        UNIQUE("invoice_id", "course_in_order_item_id")
);

INSERT INTO "invoice_order_item" ("invoice_id", "course_in_order_item_id")
SELECT
    i."id",
    coit."id"
FROM "invoice" i
JOIN "order_item" oi ON i."order_id" = oi."order_id"
JOIN "course_in_order_item" coit ON oi."order_item_id" = coit."order_item_id";

ALTER TABLE "invoice"
DROP COLUMN "order_id";

COMMIT;
